=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/cims_report.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2011 (x64) (http://www.altova.com) by cihi (CANADIAN INSTITUTE FOR HEALTH) -->
<!--W3C Schema generated by XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com)-->
<!--Please add namespace attributes, a targetNamespace attribute and import elements according to your requirements-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="workbook">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="worksheet" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="worksheet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="detailHeader" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="detail" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="header">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="startRowNumber" type="xs:integer" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paraName" type="xs:string"/>
				<xs:element name="column_number" type="xs:integer"/>
				<xs:element name="row_number" type="xs:integer" minOccurs="0" maxOccurs="1"/>
				<xs:element name="paraType" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="detailHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/ICDModifiedValidationsSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>currentYear</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>codeCount</paraName>
				<column_number>6</column_number>
				<!-- G -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>priorYear</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
		</header>
		<detail startRowNumber="10" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>dataHolding</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
			<parameter>
				<paraName>gender</paraName>
				<column_number>5</column_number>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>minAge</paraName>
				<column_number>6</column_number>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>maxAge</paraName>
				<column_number>7</column_number>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>mrdx</paraName>
				<column_number>8</column_number>
				<!-- I -->
			</parameter>
			<parameter>
				<paraName>dxType1</paraName>
				<column_number>9</column_number>
				<!-- J -->
			</parameter>
			<parameter>
				<paraName>dxType2</paraName>
				<column_number>10</column_number>
				<!-- K -->
			</parameter>
			<parameter>
				<paraName>dxType3</paraName>
				<column_number>11</column_number>
				<!-- L -->
			</parameter>
			<parameter>
				<paraName>dxType4</paraName>
				<column_number>12</column_number>
				<!-- M -->
			</parameter>
			<parameter>
				<paraName>dxType6</paraName>
				<column_number>13</column_number>
				<!-- N -->
			</parameter>
			<parameter>
				<paraName>dxType9</paraName>
				<column_number>14</column_number>
				<!-- O -->
			</parameter>
			<parameter>
				<paraName>dxTypeW</paraName>
				<column_number>15</column_number>
				<!-- P -->
			</parameter>
			<parameter>
				<paraName>dxTypeX</paraName>
				<column_number>16</column_number>
				<!-- Q -->
			</parameter>
			<parameter>
				<paraName>dxTypeY</paraName>
				<column_number>17</column_number>
				<!-- R -->
			</parameter>
			<parameter>
				<paraName>newBorn</paraName>
				<column_number>18</column_number>
				<!-- H -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/CCINewTableCodesWithCodingDirectivesSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>year</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
		</header>
		<detail startRowNumber="10" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>changeRequestId</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>changeRequestName</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/ICDModifiedValidCodeSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>currentYear</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>codeCount</paraName>
				<column_number>3</column_number>
				<row_number>5</row_number>
				<paraType>Number</paraType>
			</parameter>
		</header>
		<detail startRowNumber="10" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>currentFlag</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>priorFlag</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/QASummaryMetricsSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>fromDate</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>totalCount</paraName>
				<column_number>12</column_number>
				<!-- L -->
				<row_number>4</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>toDate</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>6</row_number>
			</parameter>
		</header>
		<detail startRowNumber="11" name="detail1">
			<parameter>
				<paraName>valid</paraName>
				<column_number>5</column_number>
				<paraType>Number</paraType>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>accepted</paraName>
				<column_number>6</column_number>
				<paraType>Number</paraType>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>translationDone</paraName>
				<column_number>7</column_number>
				<paraType>Number</paraType>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>validationDone</paraName>
				<column_number>8</column_number>
				<paraType>Number</paraType>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>realized</paraName>
				<column_number>9</column_number>
				<paraType>Number</paraType>
				<!-- H -->
			</parameter>
			<parameter>
				<paraName>qaDone</paraName>
				<column_number>10</column_number>
				<paraType>Number</paraType>
				<!-- I -->
			</parameter>
			<parameter>
				<paraName>total</paraName>
				<column_number>12</column_number>
				<paraType>Number</paraType>
				<!-- K -->
			</parameter>
		</detail>
		<detail startRowNumber="16" name="detail2">
			<parameter>
				<paraName>valid</paraName>
				<column_number>5</column_number>
				<paraType>Number</paraType>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>accepted</paraName>
				<column_number>6</column_number>
				<paraType>Number</paraType>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>translationDone</paraName>
				<column_number>7</column_number>
				<paraType>Number</paraType>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>validationDone</paraName>
				<column_number>8</column_number>
				<paraType>Number</paraType>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>realized</paraName>
				<column_number>9</column_number>
				<paraType>Number</paraType>
				<!-- H -->
			</parameter>
			<parameter>
				<paraName>qaDone</paraName>
				<column_number>10</column_number>
				<paraType>Number</paraType>
				<!-- I -->
			</parameter>
			<parameter>
				<paraName>total</paraName>
				<column_number>12</column_number>
				<paraType>Number</paraType>
				<!-- K -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/ClassificationChangeTabularReportSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>valueFrom</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>requestCategory</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>valueTo</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>5</row_number>
			</parameter>
		</header>
		<detailHeader name="detailHeader">
			<parameter>
				<paraName>year1</paraName>
				<column_number>3</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year2</paraName>
				<column_number>4</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year3</paraName>
				<column_number>5</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year4</paraName>
				<column_number>6</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year5</paraName>
				<column_number>7</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
		</detailHeader>
		<detail startRowNumber="12" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>year1</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>year2</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
			<parameter>
				<paraName>year3</paraName>
				<column_number>5</column_number>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>year4</paraName>
				<column_number>6</column_number>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>year5</paraName>
				<column_number>7</column_number>
				<!-- G -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/ClassificationChangeIndexReportSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>indexBook</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>requestCategory</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>leadIndexTerm</paraName>
				<column_number>6</column_number>
				<!-- F -->
				<row_number>5</row_number>
			</parameter>
		</header>
		<detailHeader name="detailHeader">
			<parameter>
				<paraName>year1</paraName>
				<column_number>4</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
			<parameter>
				<paraName>year2</paraName>
				<column_number>5</column_number>
				<row_number>11</row_number>
				<paraType>Number</paraType>
			</parameter>
		</detailHeader>
		<detail startRowNumber="12" name="detail1">
			<parameter>
				<paraName>hierarchicalPath</paraName>
				<column_number>2</column_number>
			</parameter>
			<parameter>
				<paraName>indexTerm</paraName>
				<column_number>3</column_number>
			</parameter>
			<parameter>
				<paraName>year1</paraName>
				<column_number>4</column_number>
			</parameter>
			<parameter>
				<paraName>year2</paraName>
				<column_number>5</column_number>
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/CCIModifiedValidationsSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>currentYear</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>codeCount</paraName>
				<column_number>6</column_number>
				<!-- G -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>priorYear</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
		</header>
		<detail startRowNumber="10" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>dataHolding</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
			<parameter>
				<paraName>gender</paraName>
				<column_number>5</column_number>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>minAge</paraName>
				<column_number>6</column_number>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>maxAge</paraName>
				<column_number>7</column_number>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>statusRef</paraName>
				<column_number>8</column_number>
				<!-- H -->
			</parameter>
			<parameter>
				<paraName>locationRef</paraName>
				<column_number>9</column_number>
				<!-- I -->
			</parameter>
			<parameter>
				<paraName>extentRef</paraName>
				<column_number>10</column_number>
				<!-- J -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/SendBackDetailSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>owner</paraName>
				<column_number>5</column_number>
				<!-- E -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>fromStatus</paraName>
				<column_number>8</column_number>
				<!-- H -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>fromDate</paraName>
				<column_number>5</column_number>
				<!-- E -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>qaErrorCount</paraName>
				<column_number>8</column_number>
				<!-- H -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>6</row_number>
			</parameter>
			<parameter>
				<paraName>toDate</paraName>
				<column_number>5</column_number>
				<!-- E -->
				<row_number>6</row_number>
			</parameter>
		</header>
		<detail startRowNumber="9" name="detail1">
			<parameter>
				<paraName>changeRequestId</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
			<parameter>
				<paraName>date</paraName>
				<column_number>3</column_number>
				<!-- C -->
			</parameter>
			<parameter>
				<paraName>classification</paraName>
				<column_number>4</column_number>
				<!-- D -->
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<column_number>5</column_number>
				<!-- E -->
			</parameter>
			<parameter>
				<paraName>owner</paraName>
				<column_number>6</column_number>
				<!-- F -->
			</parameter>
			<parameter>
				<paraName>fromStatus</paraName>
				<column_number>7</column_number>
				<!-- G -->
			</parameter>
			<parameter>
				<paraName>sendBackReason</paraName>
				<column_number>8</column_number>
				<!-- H -->
			</parameter>
		</detail>
	</worksheet>
</workbook>
