=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/cims_report.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2011 (x64) (http://www.altova.com) by cihi (CANADIAN INSTITUTE FOR HEALTH) -->
<!--W3C Schema generated by XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com)-->
<!--Please add namespace attributes, a targetNamespace attribute and import elements according to your requirements-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="workbook">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="worksheet" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="worksheet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="detailHeader" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="detail" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="header">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="startRowNumber" type="xs:integer" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paraName" type="xs:string"/>
				<xs:element name="column_number" type="xs:integer"/>
				<xs:element name="row_number" type="xs:integer" minOccurs="0" maxOccurs="1"/>
				<xs:element name="paraType" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="detailHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/MissingValidationReportSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>dataHolding</paraName>
				<column_number>5</column_number>
				<!-- F -->
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<column_number>3</column_number>
				<!-- C -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>codeFrom</paraName>
				<column_number>5</column_number>
				<!-- F -->
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>codeTo</paraName>
				<column_number>5</column_number>
				<!-- F -->
				<row_number>6</row_number>
			</parameter>
		</header>
		<detail startRowNumber="10" name="detail1">
			<parameter>
				<paraName>codeValue</paraName>
				<column_number>2</column_number>
				<!-- B -->
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/ca.cihi.cims-master/cims_web_internal/src/main/resources/report/QAErrorDescriptionsReportSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>classification</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>year</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>6</row_number>
			</parameter>
			<parameter>
				<paraName>owner</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>dateFrom</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>dateTo</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>6</row_number>
			</parameter>
			<parameter>
				<paraName>statusFrom</paraName>
				<!-- H -->
				<column_number>8</column_number>
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>errorCount</paraName>
				<!-- H -->
				<column_number>8</column_number>
				<row_number>5</row_number>
			</parameter>
		</header>
		<detail startRowNumber="9" name="detail1">
			<parameter>
				<paraName>changeRequestId</paraName>
				<!-- B -->
				<column_number>2</column_number>
			</parameter>
			<parameter>
				<paraName>sendBackDate</paraName>
				<!-- C -->
				<column_number>3</column_number>
			</parameter>
			<parameter>
				<paraName>classification</paraName>
				<!-- D -->
				<column_number>4</column_number>
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<!-- E -->
				<column_number>5</column_number>
			</parameter>
			<parameter>
				<paraName>owner</paraName>
				<!-- F -->
				<column_number>6</column_number>
			</parameter>
			<parameter>
				<paraName>fromStatus</paraName>
				<!-- G -->
				<column_number>7</column_number>
			</parameter>
			<parameter>
				<paraName>sendBackReason</paraName>
				<!-- H -->
				<column_number>8</column_number>
			</parameter>
		</detail>
	</worksheet>
</workbook>

=== MANNEMPRATAPVARUN/CIMS/cims_web_internal/src/main/resources/report/ReviewGroupOutboundQuestionsTabularReportSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cims_report.xsd">
	<worksheet name="CIMS Report">
		<header>
			<parameter>
				<paraName>year</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>classification</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>language</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>6</row_number>
			</parameter>
			<parameter>
				<paraName>requestCategory</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>7</row_number>
			</parameter>
			<parameter>
				<paraName>reviewGroup</paraName>
				<!-- C -->
				<column_number>3</column_number>
				<row_number>8</row_number>
			</parameter>
			<parameter>
				<paraName>valueFrom</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>4</row_number>
			</parameter>
			<parameter>
				<paraName>valueTo</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>5</row_number>
			</parameter>
			<parameter>
				<paraName>patternTopic</paraName>
				<!-- E -->
				<column_number>5</column_number>
				<row_number>8</row_number>
			</parameter>
		</header>
		<detail startRowNumber="12" name="detail1">
			<parameter>
				<paraName>changeRequestId</paraName>
				<!-- B -->
				<column_number>2</column_number>
			</parameter>
			<parameter>
				<paraName>questionForReviewerId</paraName>
				<!-- C -->
				<column_number>3</column_number>
			</parameter>
			<parameter>
				<paraName>questionForReviewerTxt</paraName>
				<!-- D -->
				<column_number>4</column_number>
			</parameter>
		</detail>
	</worksheet>
</workbook>
